package nlp.future

/**
 * Created by Aimingnie on 7/7/15.
 */
object FutureRules {

  val patternFuture = List(
    "(VP < (VBG < going) < (S < (VP < TO)))",
    "(VP < (VBG < going) > (PP < TO))",
    "MD < will",
    "MD < ‘ll’",
    "MD < shall",
    "MD < would",
    "MD < 'd’",
    "VP < VBD << would",
    "MD < may",
    "MD < might",
    "MD < should",
    "MD < can",
    "MD < could",
    "VP < VBD << could",
    "MD < must",
    "MD < ought",
    "VB|VBD|VBG|VBN|VBP|VBZ < need|needs|needed|needing",
    "VP [ << have | << has | << had << having ] < ( S < ( VP < TO ))",
    "VP [ << supposed] < ( S < ( VP < TO ) )",
    "ADJP < ( JJ [ < unable ]) < ( S < ( VP < TO ))",
    "ADJP < ( JJ [ < able]) < ( S < ( VP < TO ))",
    "VP < ( PP < ( IN < about|of ) < ( S < ( VP <+( VP ) VBG )))",
    "SBAR < WHNP|WHADVP < (S < (VP < TO ))",
    "S < ( VP < TO < ( VP < VB ))",
    "VP [ << look | << looks | << looking]  << forward",
    "VP << want|wants|wanted|wanting|hope|hopes|hoped|hoping",
    "goal|goals|ambition",
    "upcoming|future|impending",
    "plan|plans|planned",
    "NP << need|needs",
    "tomorrow|soon|later",
    "NP << (week|weekend|month|year| ,, next)",
    "tonight",
    "NP << (week|weekend|month|year| ,, this)",
    "NP << this [ << ( weekend ,, this ) | << ( evening ,, this )]",
    "IN $ (NP < CD << hours|days|weeks|months|seasons|years)",
    "IN $ (NP < DT <<  hour|day|week|weekend|month|season|year)",
    "JJ < next $ (NN < hour|day|week|weekend|month|season|year)",
    "IN < CD << hour|day|week|weekend|month|season|year"
  )

  val patternFuture2 = List(
    "MD < will|'ll",
    "MD < wo",
    "MD < shall",
    "MD < would|'d",
    "MD < may",
    "MD < might",
    "MD < should",
    "MD < can",
    "MD < ca",
    "MD < could",
    "MD < must",
    "VBG < gon",
    "(VBG < going) < (S < (VP < TO))",
    "S|VP|ADJP|ADVP < (IN|RB < about) $ (S < (VP < TO))",
    "S < (RB < about|About) < (VP < (TO < to))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < (S < ( VP < TO))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < NP",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /hav|had/) < (S < (VP < TO))",
    "VP < (VBN < supposed) < (S < (VP < TO))",
    "S < (NP $ (RB < better) $ VP)",
    "S < (NP $ (ADVP <<# better) $ VP)",
    "VB|VBD|VBG|VBN|VBP|VBZ < /want/",
    "VBP < wan",
    "VP < (PP < (IN < about|of ) !< (RB < instead) < ( S < ( VP <+(VP) VBG)))",
    "ROOT < (S|SQ <, (VP !< TO|S !< VBG))",
    "ROOT < (S|SQ <, INTJ < (VP !< TO|S !< VBG))",
    "SBAR < WHNP|WHADVP < (S < (VP < TO ))",
    "VP !< (__ < /seem|appear|happen/) < (S < ( VP < TO < VP))",
    "ADJP < (JJ < able|enough|willing) < (S < ( VP < TO < VP))  ",
    "ADJP < (JJ < likely|excited) < (S < ( VP < TO < VP))",
    "NP < (S < ( VP < TO < VP))        	",
    "S < VP  << /look/ << forward",
    "VB|VBD|VBG|VBN|VBP|VBZ << /hope|hoping/",
    "B|VBD|VBG|VBN|VBP|VBZ < plan|plans|planned|planning",
    "VP < (MD < ca) < (VP < (VB < wait))",
    "VP < (MD < could) < (RB < n't) < (VP < (VB < wait))",
    "VB|VBD|VBG|VBN|VBP|VBZ < /choos/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /schedul/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /consider/",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /figur/) < (PRT < (RP < out))",
    "NN|NNS < need",
    "NN|NNS << /hope/",
    "NN|NNS < /goal/",
    "NN|NNS < plan|plans",
    "JJ|NN < due",
    "NN < future",
    "NN|NNS < /schedule/",
    "NN|NNS < /consequence/",
    "NN|NNS < /choice/",
    "VBG|JJ < upcoming",
    "JJ < imminent",
    "JJ < future",
    "JJ < potential",
    "JJ < impending",
    "JJ < ready",
    "RB < potentially",
    "RB < soon",
    "RB < ahead",
    "RB < sometime",
    "RB < finna|funna"
  ) //60 rules

  val patternFuture2_1 = List(
    "ADJP < (JJ < able|enough|willing) < (S < (VP < TO < VP))",
    "ADJP < (JJ < likely|excited) < (S < (VP < TO < VP))",
    "S|VP|ADJP|ADVP < (IN|RB < about) $ (S < (VP < TO))",
    "S < (RB < about) < (VP < (TO < to))",
    "NP < (S < (VP < TO < VP))",
    "SBAR < WHNP|WHADVP < (S < (VP < TO))",
    "VP !< (__ < /seem|appear|happen/) < (S < ( VP < TO < VP))",
    "VP < (PP < (IN < about|of ) !< (RB < instead) < (S < ( VP <+(VP) VBG)))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < (S < ( VP < TO))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < NP",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /hav|had/) < (S < (VP < TO))",
    "VP < (VBN < supposed) < (S < (VP < TO))",
    "VB|VBD|VBG|VBN|VBP|VBZ < /want/",
    "VBP < wan",
    "S < (NP $ (RB < better) $ VP)",
    "S < (NP $ (ADVP <<# better) $ VP)",
    "VP < (MD < /ought/) < (S < ( VP < TO))",
    "ROOT < (S|SQ <, (VP !< TO|S !< VBG))",
    "ROOT < (S|SQ <, INTJ < (VP !< TO|S !< VBG))",
    "ROOT < (S|SQ <, (NP < (NN < someone|somebody)) < (VP < VB|VBP !< TO|S !< VBG))",
    "VBG < gon",
    "(VBG < going) < (S < (VP < TO))",
    "MD < will|'ll",
    "MD < wo",
    "MD < shall",
    "MD < would|'d",
    "MD < may",
    "MD < might",
    "MD < should",
    "MD < can",
    "MD < ca",
    "MD < could",
    "MD < must",
    "VP < (MD < ca) < (VP < (VB < wait))",
    "VP < (MD < could) < (RB < n't) < (VP < (VB < wait))",
    "S < VP << /look/ << forward",
    "VB|VBD|VBG|VBN|VBP|VBZ << /hope|hoping/",
    "VB|VBD|VBG|VBN|VBP|VBZ < plan|plans|planned|planning",
    "VB|VBD|VBG|VBN|VBP|VBZ < /choos/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /schedul/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /consider/",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /figur/) < (PRT < (RP < out))",
    "NN|NNS < need",
    "NN|NNS << /hope/",
    "NN|NNS < /goal/",
    "NN|NNS < /choice/",
    "NN|NNS < /consequence/",
    "NN|NNS < plan|plans",
    "NN|NNS < /schedule/",
    "NN|JJ < due",
    "NN|JJ < future",
    "VBG|JJ < upcoming",
    "JJ < imminent",
    "JJ < future",
    "JJ < impending",
    "JJ < ready",
    "JJ < potential",
    "RB < soon",
    "RB < ahead",
    "RB < sometime",
    "RB < potentially",
    "RB < finna|funna",
    "NN|RB < tonight",
    "NN|RB < tomorrow",
    "(PP  < (IN < from) < (NP|ADVP < (RB < now)))",
    "NP < (RBR|RB|JJ < later) < (DT < this)",
    "NP|VP < (ADVP|NP < (JJ|RB < later)) < (NP|NN < today)",
    "S <+ (!S) (PP < (IN < at) < (NP < CD)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (RB < later) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))"
  ) //69 rules

  val patternFuture2_2_2 = List(
    "ADJP < (JJ < able|enough|willing) < (S < (VP < TO < VP))",
    "ADJP < (JJ < likely|excited) < (S < (VP < TO < VP))",
    "S|VP|ADJP|ADVP < (IN|RB < about) $ (S < (VP < TO))",
    "S < (RB < about) < (VP < (TO < to))",
    "NP !< NP|JJ < (S < (VP < TO < VP))",
    "SBAR < WHNP|WHADVP < (S < (VP < TO))",
    "__  !< (RB < n't|not) < (VP !< (__ < /seem|appear|happen|used|begin|began|love|like|tried|fail|decline|propose/) < (S < (VP < TO < VP)))",
    "VP < (PP < (IN < about|of ) !< (RB < instead) < (S < (VP <+(VP) VBG)))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < (S < (VP < TO))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < NP",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /hav|had|has/) < (S < (VP < TO))",
    "VP < (VBN < supposed) < (S < (VP < TO))",
    "VB|VBD|VBG|VBN|VBP|VBZ < /want/",
    "VBP < wan",
    "S < (NP $ (RB < better) $ VP)",
    "S < (NP $ (ADVP <<# better) $ VP)",
    "VP < (MD < /ought/) < (S < ( VP < TO))",
    "ROOT < (S|SQ <, (VP !< TO|S !< VBG))",
    "ROOT < (S|SQ <, INTJ < (VP !< TO|S !< VBG))",
    "ROOT < (S|SQ <, (NP < (NN < someone|somebody)) < (VP < VB|VBP !< TO|S !< VBG))",
    "VBG < gon",
    "VP < (VB|VBG|VBP|VBZ|VBD|VBN < go|going|goes|went|gone) < (S < (VP < TO))",
    "MD < will|'ll",
    "MD < wo",
    "MD < shall",
    "MD < would|'d",
    "VP < (MD < may) < (VP !< (VB < be|have))",
    "MD < might",
    "MD < should",
    "MD < can",
    "MD < ca",
    "MD < could",
    "VP < (MD < must) < (VP !< (VB < be|have))",
    "VP < VBP << (PP < S)",
    "VP < VBZ|VBG|VBP|VB !<< is|are|have << (PP < (IN < for) << NNS)",
    "VP < (MD < ca) < (VP < (VB < wait))",
    "VP < (MD < could) < (RB < n't) < (VP < (VB < wait))",
    "S < VP << /look/ << forward",
    "VB|VBD|VBG|VBN|VBP|VBZ << /hope|hoping/",
    "VB|VBD|VBG|VBN|VBP|VBZ < plan|plans|planned|planning",
    "VB|VBD|VBG|VBN|VBP|VBZ < /choos/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /schedul/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /consider/",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /figur/) < (PRT < (RP < out))",
    "VB|VBD|VBG|VBN|VBP|VBZ < /ban/",
    "VB|VBD|VBG|VBN|VBP|VBZ < fancy|fancies|fancying|fancied",
    "VB|VBD|VBG|VBN|VBP|VBZ < /guarantee/",
    "VB|VBD|VBG|VBN|VBP|VBZ < worry|worries|worrying|worried",
    "NN|NNS < need",
    "NN|NNS << /hope/",
    "NN|NNS < /goal/",
    "NN|NNS < /choice/",
    "NN|NNS < /consequence/",
    "NN|NNS < /plan/",
    "NN|NNS < /schedule/",
    "NN|JJ < future",
    "NN|NNS < /due/",
    "NN|NNS < eligibility|eligibilities",
    "NN|NNS < fancy|fancies",
    "NN|NNS < ban|bans",
    "NN|NNS < /budget/",
    "NN|NNS < /deadline/",
    "NN|NNS < /expectation/",
    "NN|NNS < /guarantee/",
    "NN|NNS < /need/",
    "NN|NNS < necessity|necessities",
    "NN|NNS < /option/",
    "NN|NNS < possibility|possibilities",
    "NN|NNS < /will/",
    "NN|NNS < worry|worries",
    "NN|NNS < /ambition/",
    "VBG|JJ < upcoming",
    "VBG|JJ < pending",
    "VBN|JJ < /worr/",
    "VBN|JJ < excited",
    "ADJP < (JJ < due) !< (PP < TO)",
    "JJ < imminent",
    "JJ < future",
    "JJ < impending",
    "JJ < ready",
    "JJ < potential|possible",
    "JJ < eligible",
    "JJ < patient|impatient",
    "JJ < next",
    "RB < soon",
    "RB < ahead",
    "RB < sometime",
    "RB < potentially|possibly",
    "RB < finna|funna",
    "RB < patiently|impatiently",
    "NN|RB < tonight",
    "NN|RB < tomorrow",
    "NP < (JJ < next) < TN|TC",
    "NP < (JJ < coming) < TN|TC",
    "PP  < (IN < by) < (NP < (DT < the|this) < TN|TC)",
    "PP  < (IN < by) < (NP < (DT < the|this) !< past|last|previous < TN|TC)",
    "PP  < (IN < by) < TN|TC",
    "(PP  < (IN < from) < (NP|ADVP < (RB < now)))",
    "NP < (RBR|RB|JJ < later) < (DT < this)",
    "NP|VP < (ADVP < (RB < later)) < (NP < (TN < today))",
    "NP < (RB|JJ < Later|later) < (TN < today)",
    "PP < (IN < by) < (NP < (NP < DT) < (PP < TC|TN))",
    "S <+ (!S) (NP < (DT < this < TN|TC)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (PP < (IN < in|for) < (NP <, DT|CD|JJ < TC|TN)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (PP < (IN < at) < (NP < CD)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (PP  < (IN < on|for) < TN) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (RB < later) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (ADVP < TN|TC < (RB < away)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (VP < TN|TC < (ADVP < (RB < away))) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (TN < today) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) PP < (IN < in) < (NP < (NP <, DT < (NN < couple)) < (PP < (IN < of) < TN|TC)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))"
  )

  val patternsPast = List(
    "VBD",
    "VP [ < ( VB < have ) | < ( VBP [ < have | < 've ] ) | < ( VBZ [ < has | < 's ] ) ] < ( VP < VBN )",
    "S < (when < VBD) <<  MD < would",
    "VP [ < ( VB [ < remember | < miss | < regret | < recall | < recollect ] ) | < ( VBP [ < remember | < miss | < regret | < recall | < recollect ] ) | < ( VBZ [ < remembers | < misses | < regrets | < recalls | < recollects ] ) ] < NP",
    "forgets|forgot|forgotten|forget !.to",
    "VP [ < ( VB < thank ) | < ( VBP < thank ) | < ( VBZ < thanks ) | < ( VBG < thanking ) ] < ( PP < ( IN < for ) )",
    "VP << wish|wishes|wished|wishing",
    "NP < ( JJ|NN < past )",
    "NP < ( NP < ( NNS [ < thanks | < congratulations | < congrats | < props | < kudos | < praise ] ) ) < ( PP < ( IN < for ) )",
    "NP << regret|regrets",
    "yesterday",
    "NP < (JJ < last) < (NN < week|weekend|month|year)",
    "NP < (JJ < last) < (NNS < weeks|weekends|months|years)",
    "proud . of|former|previous",
    "ago",
    "so.far"
  ) //16

  val patternPresent = List("VBZ", "VBG", "VBP")

}
